# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: "build_artifact"
        path: target/*.jar

  release:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.9
      with:
        name: "build_artifact"
    - name: Tar the Jars
      run: tar czvf ${{ github.ref_name }}.tar.gz *.jar
    - uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: ${{ github.ref_name }}
        files: "${{ github.ref_name }}.tar.gz"
        make_latest: true
